version: "1"
rules:
  - base: stable
    upstream: testing
    mergeMethod: rebase
    mergeUnstable: false
    reviewers:
      - castrojo
      - tulilirockz
    conflictReviewers:
      - castrojo
      - tulilirockz
  - base: testing
    upstream: next
    mergeMethod: rebase
    mergeUnstable: false
    reviewers:
      - castrojo
      - tulilirockz
    conflictReviewers:
      - castrojo
      - tulilirockz
label: "promotion"
conflictLabel: "promotion-conflict"
